services: 
 s3app:
  image: postgres:latest
  container_name: 68-s3-app
  environment:
    POSTGRES_USER: ${DATABASE_USER}
    POSTGRES_PASSWORD: ${DATABASE_PASS}
    POSTGRES_DB: ${DATABASE_NAME}
  ports:
   - ${DATABASE_PORT}

